### ISSUE TITLE
对话不扣费，并且后台消息列表的消息状态都是异常

### ISSUE THREAD

**Issue by southcat** [jarvis2f/ais-ninja#16]
前台可以正常对话但是不扣费 

[36mOpenAI Error: Error: Request failed with status code 400
    at createError (/app/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/server/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/app/server/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at RedirectableRequest._processResponse (/app/server/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/app/server/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)[39m
[01:15:36.742] [31mERROR[39m (openai/50): [36mOpenAI Error: Error: Request failed with status code 400
    at createError (/app/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/server/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/app/server/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at RedirectableRequest._processResponse (/app/server/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/app/server/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)[39m
[01:15:46.432] [31mERROR[39m (openai/50): [36mOpenAI Error: Error: Request failed with status code 400
    at createError (/app/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/server/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/app/server/node_modules/axios/lib/adapters/http.js:278:9)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at RedirectableRequest._processResponse (/app/server/node_modules/follow-redirects/index.js:356:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/app/server/node_modules/follow-redirects/index.js:62:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)[39m
(sequelize) Warning: Model "RedemptionCode" is declaring public class fields for attribute(s): "ip", "user_id", "key", "value", "status", "type", "end_time", "level", "create_time", "update_time".
These class fields are shadowing Sequelize's attribute getters & setters.

**Comment by jarvis2f** [comment]
没扣费是不是倍率没有设置，消息列表那个状态不影响的

**Comment by southcat** [comment]
> 没扣费是不是倍率没有设置，消息列表那个状态不影响的

{
    "gpt-3.5-turbo": {
      "input": "10",
      "output": "10"
    },
    "gpt-3.5-turbo-16k": {
        "input": "10",
        "output": "10"
      },
      "gpt-3.5-turbo-0613": {
        "input": "10",
        "output": "10"
      },
      "gpt-3.5-turbo-16k-0613": {
        "input": "10",
        "output": "10"
      },
      "gpt-3.5-turbo-0301": {
        "input": "10",
        "output": "10"
      }
}倍率设置另一个都是5 就是不扣费
